name: vango
description: "VanGo: Aplicativo para gerenciamento de transporte escolar e universitário."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  path: ^1.9.0


  mask_text_input_formatter: ^2.9.0


  # Mapas
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  google_places_flutter: ^2.0.4

  # Firebase

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  firebase_messaging: ^16.0.4
  cloud_functions: ^6.0.4

  # Search

  # Imagens
  image_picker: ^1.2.1
  permission_handler: ^11.0.1

  # Utilitários e ícones
  flutter_dotenv: ^5.1.0
  intl: ^0.20.2
  http: ^1.2.1
  flutter_polyline_points: ^2.0.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0 # Add this line
  sqflite_common_ffi: ^2.3.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#B5FF2A" # mesmo verde do ícone
  image: assets/splash_icon_hd.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#B5FF2A"
    image: assets/splash_icon_hd.png

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/.env
